# Generated by Django 5.1.7 on 2025-03-24 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0008_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id_ordem', models.AutoField(primary_key=True, serialize=False)),
                ('matricula_vendedor', models.CharField(max_length=30)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordens_servico', to='cadastro.cliente')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordens_servico', to='cadastro.pedido')),
            ],
            options={
                'db_table': '"comercial"."ordem_servico"',
            },
        ),
    ]
