# Generated by Django 5.1.7 on 2025-03-24 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0008_cliente'),
        ('comercial', '0002_itenspedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecimento',
            fields=[
                ('id_fornecimento', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateTimeField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('distribuidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fornecimentos', to='cadastro.distribuidor')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fornecimentos', to='cadastro.fornecedor')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fornecimentos', to='cadastro.produto')),
            ],
            options={
                'db_table': '"comercial"."fornecimento"',
            },
        ),
    ]
