# Generated by Django 5.1.7 on 2025-03-24 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0003_fornecimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itenspedido',
            name='pedido',
        ),
        migrations.RemoveField(
            model_name='itenspedido',
            name='produto',
        ),
        migrations.DeleteModel(
            name='Fornecimento',
        ),
        migrations.DeleteModel(
            name='ItensPedido',
        ),
    ]
