# Generated by Django 5.1.7 on 2025-03-24 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0010_produto'),
        ('comercial', '0004_remove_itenspedido_pedido_remove_itenspedido_produto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecimento',
            fields=[
                ('id_fornecimento', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateTimeField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('distribuidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fornecimentos', to='cadastro.distribuidor')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fornecimentos', to='cadastro.fornecedor')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fornecimentos', to='cadastro.produto')),
            ],
            options={
                'db_table': '"comercial"."fornecimento"',
            },
        ),
        migrations.CreateModel(
            name='ItensPedido',
            fields=[
                ('id_itensPedido', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade', models.IntegerField()),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_pedido', to='cadastro.pedido')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_pedido', to='cadastro.produto')),
            ],
            options={
                'db_table': '"comercial"."itens_pedido"',
            },
        ),
    ]
