# Generated by Django 5.1.7 on 2025-03-25 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0010_produto'),
        ('comercial', '0006_alter_fornecimento_distribuidor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordemservico',
            name='matricula_vendedor',
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordens_servico', to='cadastro.vendedor'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordens_servico', to='cadastro.cliente'),
        ),
    ]
