# Generated by Django 5.1.7 on 2025-04-12 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0010_produto'),
        ('comercial', '0007_remove_ordemservico_matricula_vendedor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id_pagamento', models.AutoField(primary_key=True, serialize=False)),
                ('forma_pagamento', models.CharField(choices=[('cartao', 'Cartão'), ('boleto', 'Boleto'), ('pix', 'Pix'), ('berries', 'Berries')], max_length=20)),
                ('status_pagamento', models.CharField(choices=[('pendente', 'Pendente'), ('confirmado', 'Confirmado'), ('recusado', 'Recusado')], max_length=20)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pagamento', to='cadastro.pedido')),
            ],
            options={
                'db_table': '"comercial"."pagamento"',
            },
        ),
    ]
