# Generated by Django 5.1.7 on 2025-04-15 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0014_pedido_cupom'),
        ('comercial', '0008_pagamento'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ordemservico',
            constraint=models.UniqueConstraint(fields=('pedido',), name='unique_pedido_ordem_servico'),
        ),
    ]
