# Generated by Django 5.1.7 on 2025-03-23 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id_fornecedor', models.AutoField(primary_key=True, serialize=False)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('nome', models.CharField(max_length=255)),
            ],
            options={
                'db_table': '"cadastro"."fornecedor"',
            },
        ),
    ]
