# Generated by Django 5.1.7 on 2025-03-24 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0005_produto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distribuidor',
            fields=[
                ('id_distribuidor', models.AutoField(primary_key=True, serialize=False)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('nome', models.CharField(max_length=255)),
            ],
            options={
                'db_table': '"cadastro"."distribuidor"',
            },
        ),
    ]
