# Generated by Django 5.1.7 on 2025-03-24 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0006_distribuidor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('data_pedido', models.DateTimeField()),
            ],
            options={
                'db_table': '"cadastro"."pedido"',
            },
        ),
    ]
