# Generated by Django 5.1.7 on 2025-03-24 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0008_cliente'),
        ('comercial', '0004_remove_itenspedido_pedido_remove_itenspedido_produto_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Produto',
        ),
    ]
