# Generated by Django 5.1.7 on 2025-03-24 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0009_delete_produto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('cod_produto', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('valor_produto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estoque', models.IntegerField()),
                ('desc_produto', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': '"cadastro"."produto"',
            },
        ),
    ]
