# Generated by Django 5.1.7 on 2025-04-12 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0010_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cliente_especial',
            field=models.BooleanField(default=False),
        ),
    ]
