# Generated by Django 5.1.7 on 2025-04-14 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0012_alter_cliente_telefone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='cliente_especial',
        ),
        migrations.AddField(
            model_name='cliente',
            name='cidade',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
